import { NextRequest } from "next/server";
import type {
  InterviewQuestion,
  WeaknessReport,
  StrengthHighlight,
  GitHubProfile,
} from "@/lib/types";

export async function POST(request: NextRequest) {
  const body = await request.json();
  const { format, profile, questions, weaknesses, strengths } = body as {
    format: "markdown" | "pdf";
    profile: GitHubProfile;
    questions: InterviewQuestion[];
    weaknesses: WeaknessReport[];
    strengths: StrengthHighlight[];
  };

  if (format === "markdown") {
    let md = `# Interview Prep Sheet — ${profile.login}\n\n`;
    md += `> Generated by RepoInterview AI\n\n`;
    md += `**Name:** ${profile.name || "N/A"} | **Bio:** ${profile.bio || "N/A"} | **Repos:** ${profile.public_repos} | **Followers:** ${profile.followers}\n\n---\n\n`;

    if (strengths.length > 0) {
      md += `## Strengths\n\n`;
      for (const s of strengths) {
        md += `- **${s.repo}** (${s.category}): ${s.message}\n`;
      }
      md += `\n`;
    }

    if (weaknesses.length > 0) {
      md += `## Weaknesses\n\n`;
      for (const w of weaknesses) {
        md += `### ${w.repo} — Score: ${w.score}/100\n`;
        for (const issue of w.issues) {
          md += `- [${issue.severity.toUpperCase()}] ${issue.message}\n`;
        }
        md += `\n`;
      }
    }

    md += `## Interview Questions\n\n`;
    for (const q of questions) {
      md += `### [${q.category}] ${q.question}\n\n`;
      md += `**Related Repo:** ${q.relatedRepo}`;
      if (q.relatedFile) md += ` | **File:** ${q.relatedFile}`;
      md += `\n\n`;
      md += `**Model Answer:**\n${q.modelAnswer}\n\n`;
      md += `**Key Points:**\n`;
      for (const kp of q.keyPoints) md += `- ${kp}\n`;
      md += `\n**Common Mistakes:**\n`;
      for (const cm of q.commonMistakes) md += `- ${cm}\n`;
      md += `\n**Follow-up:** ${q.followUp}\n\n---\n\n`;
    }

    return new Response(md, {
      headers: {
        "Content-Type": "text/markdown",
        "Content-Disposition": `attachment; filename="interview-prep-${profile.login}.md"`,
      },
    });
  }

  return Response.json({ error: "PDF export not yet supported" }, { status: 400 });
}
